### ISSUE TITLE
Errors with own data

### ISSUE THREAD

**Issue by aaltenbernd** [phamquiluan/baro#11]
Hello, 

I'm interested in testing Baro for a project I'm currently working on.
I have fetched some data from the sock-shop microservice application through prometheus.
However, I got some errors when entering the data. Maybe you got an idea?
Is there anything else to consider apart from the format of the data? 

```
% python test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    anomalies = bocpd(data) 
  File "/Users/aaltenbernd/Desktop/MicroRCA/baro/baro/anomaly_detection.py", line 111, in bocpd
    R, maxes = online_changepoint_detection(
  File "/Users/aaltenbernd/Desktop/MicroRCA/baro/baro/_bocpd.py", line 204, in online_changepoint_detection
    predprobs = log_likelihood_class.pdf(x)
  File "/Users/aaltenbernd/Desktop/MicroRCA/baro/baro/_bocpd.py", line 101, in pdf
    ret[i] = ss.multivariate_t.pdf(x=data, df=df, loc=loc, shape=shape)
  File "/Users/aaltenbernd/Desktop/MicroRCA/baro/env/lib/python3.8/site-packages/scipy/stats/_multivariate.py", line 4330, in pdf
    shape_info = _PSD(shape, allow_singular=allow_singular)
  File "/Users/aaltenbernd/Desktop/MicroRCA/baro/env/lib/python3.8/site-packages/scipy/stats/_multivariate.py", line 162, in __init__
    s, u = scipy.linalg.eigh(M, lower=lower, check_finite=check_finite)
  File "/Users/aaltenbernd/Desktop/MicroRCA/baro/env/lib/python3.8/site-packages/scipy/linalg/_decomp.py", line 561, in eigh
    w, v, *other_args, info = drv(a=a1, **drv_args, **lwork_args)
_flapack.error: (il>=1&&il<=n) failed for 6th keyword il: dsyevr:il=1
```

Here is a cutout of the data. There are more metrics but everything has the same format.
[data.csv](https://github.com/user-attachments/files/16819946/data.csv)

**Comment by phamquiluan** [comment]
@aaltenbernd 

You should have some `latency` and `error` columns.

```python
        if "latency" in c or "latency-50" in c or "_error" in c:
```

https://github.com/phamquiluan/baro/blob/main/baro/anomaly_detection.py#L96

**Comment by phamquiluan** [comment]
I have inspected your data. There is no latency or error columns. Hence the bocpd can't be run.
![image](https://github.com/user-attachments/assets/023c9179-6c6a-4561-be8b-5b7e37e6c0c7)
